export const VALIDATOR_TYPE_REQUIRE = 'REQUIRE';
export const VALIDATOR_TYPE_SUCCESS = 'SUCCESS';
export const VALIDATOR_TYPE_REMOVE = 'REMOVE';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT'
export const UPLOAD_AVATAR = "UPLOAD_AVATAR"
export const GET_AVATAR = "GET_AVATAR"

export const GET_PROFILE= 'GET_PROFILE';
export const GET_STATIC_PROFILE="GET_STATIC_PROFILE"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const CLEAR_LOGOUT_PROFILE = "CLEAR_LOGOUT_PROFILE"
export const DELETE_PROFILE = "DELETE_PROFILE"

export const GET_BUZZINGS= 'GET_BUZZINGS';
export const BUZZING_ERROR= 'BUZZING_ERROR';
export const ADD_BUZZ = "ADD_BUZZ"
export const DELETE_BUZZ = "DELETE_BUZZ"
export const BUZZINGS_LIKES = 'BUZZINGS_LIKES'
export const ADD_COMMENT = "ADD_COMMENT"
export const DELETE_COMMENT="DELETE_COMMENT"
export const CHANGED_AVATAR_UPDATE = "CHANGED_AVATAR_UPDATE"
